pygments: true
auto: true

title: Voters Registration Centres | By Code4Kenya
url: http://voters.code4kenya.org

author :
  name : David Lemayian
  email : david@code4kenya.com
  github : http://github.com/DavidLemayian
  twitter : DavidLemayian